sudo: false
dist: trusty
language: node_js

node_js:
  - '8'

addons:
  chrome: stable

cache:
  directories:
  - node_modules

after_script: "cat ./frontend/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"