#! /bin/sh

if ! tmux has-session -t web-starter-kit
then
    tmux new-session -s web-starter-kit -n Server -d

    # create moar windows
    tmux new-window -t web-starter-kit:1 -n Client
    tmux new-window -t web-starter-kit:2 -n TestClient
    tmux new-window -t web-starter-kit:3 -n TestServer
    tmux new-window -t web-starter-kit:4 -n Zsh

    # run the server in the first window
    tmux send-keys -t web-starter-kit:0.0 'cd ~/dev/web-starter-kit && npm run start:server' C-m

    # run the client in the second window
    tmux send-keys -t web-starter-kit:1.0 'cd ~/dev/web-starter-kit/frontend && npm start' C-m

    # run the client tests in the third window
    tmux send-keys -t web-starter-kit:2.0 'cd ~/dev/web-starter-kit/frontend && npm run test' C-m

    # run the server tests in the fourth window
    tmux send-keys -t web-starter-kit:3.0 'cd ~/dev/web-starter-kit && npm run test:server:watch' C-m

    # just get to the proper path in the last window
    tmux send-keys -t web-starter-kit:4.0 'cd ~/dev/web-starter-kit' C-m

    # select the server window and pane
    tmux select-window -t web-starter-kit:0.0
fi
tmux attach -t web-starter-kit
